project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

projeto/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

recipes/urls.py
from django.urls import path

from . import views

app_name = 'recipes'
urlpatterns = [

    path('', views.home, name="home"),
    path('recipes/category/<int:category_id>/',
         views.category, name="category"),
    path('recipes/<int:id>/', views.recipe, name="recipe"),
    # path('sobre/', sobre),
    # path('contato/', contato ),
]

recipes/models.py
from django.contrib.auth.models import User
from django.db import models


class Category(models.Model):
    name = models.CharField(
        max_length=65
    )

    def __str__(self):  # mostra o nome dos itens no menu adm
        return self.name


class Recipe(models.Model):
    title = models.CharField(
        max_length=65
    )

    description = models.CharField(
        max_length=165
    )

    slug = models.SlugField()
    preparation_time = models.IntegerField()
    preparation_time_unit = models.CharField(
        max_length=65
    )

    servings = models.IntegerField()
    servings_unit = models.CharField(
        max_length=65
    )

    preparation_steps = models.TextField()

    preparation_steps_is_html = models.BooleanField(
        default=False
    )

    created_at = models.DateTimeField(
        auto_now=False,
        auto_now_add=True
    )

    update_at = models.DateTimeField(
        auto_now=True,
        auto_now_add=False
    )

    is_published = models.BooleanField(
        default=False
    )

    cover = models.ImageField(
        upload_to='recipes/covers/%Y/%m/%d/',
        height_field=None,
        width_field=None,
        max_length=None,
        blank=True,
        default=''
    )

    category = models.ForeignKey(
        Category,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        default=None
    )

    author = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True
    )

    def __str__(self):
        return self.title

recipes/views.py
from django.shortcuts import get_list_or_404, get_object_or_404, render

from recipes.models import Recipe

# from utils.recipes.factory import make_recipe


def home(request):
    recipes = Recipe.objects.filter(
        is_published=True
    ).order_by('-id')
    return render(request, 'recipes/pages/home.html', context={
        'recipes': recipes,
    })


def category(request, category_id):
    recipes = get_list_or_404(
        Recipe.objects.filter(
            category__id=category_id,
            is_published=True,
        ).order_by('-id')
    )

    return render(request, 'recipes/pages/category.html', context={
        'recipes': recipes,
        'title': f'{recipes[0].category.name} - Categoria | '
    })


def recipe(request, id):
    recipe = get_object_or_404(
        Recipe,
        pk=id,
        is_published=True,
    )

    return render(request, 'recipes/pages/recipe-view.html', context={
        'recipe': recipe,
        'is_detail_page': True
    })

# # #     # def sobre(request):

# # #     # return  render(request, 'recipes/sobre.html')

    # def contato(request):
    # return render(request, 'recipes/contato.html')

recipes/templates/recipes/pages/category.html
{% extends 'global/base.html' %}

{% block title %}{{title}}{% endblock title %}

{% block content %}
<div class="main-content main-content-detail container">
  {% for recipe in recipes %}
    {% include 'recipes/reusable/recipe.html' %}
  {% endfor %}
  
</div>


{% endblock content %}

 

recipes/templates/recipes/pages/home.html
{% extends 'global/base.html' %}

{% block title %}Home |{% endblock title %}Home |

{% block content %}
<div class="main-content main-content-list container">
  {% for recipe in recipes %}
    {% include 'recipes/reusable/recipe.html' %}
  {% empty %}
    <div class="center m-y">
      <h1>No recipes found here man!!!!</h1>
    </div>
  {% endfor %}
  
</div>


{% endblock content %}

 

recipes/templates/recipes/pages/recipe-view.html
{% extends 'global/base.html' %}

{% block title %}{{recipe.title}} | {% endblock title %}

{% block content %}
<div class="main-content main-content-detail container">
  {% include 'recipes/reusable/recipe.html' %}
</div>
{% endblock content %}



 

recipes/templates/recipes/reusable/footer.html
<footer class="main-footer">
  <div class="developer">
    <a href="http://" target="_blank" rel="noopener noreferrer">By Fabiano Lopes</a>
  </div>
  <div class="powered">
    <a href="http://" target="_blank" rel="noopener noreferrer">Powered by Django</a>
  </div>
</footer>

recipes/templates/recipes/reusable/head.html
{% load static %}

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@900&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'recipes/css/style.css' %}">
  
  

recipes/templates/recipes/reusable/header.html
<header class="main-header-container">
  <div class="main-header container">
    <h1>
      <a class="main-logo" href="{% url 'recipes:home' %}">
        <i class="bi bi-fire main-logo-icon"></i>
        <span class="main-logo-text">Recipes</span>
      </a>

    </h1>

  </div>
</header>

recipes/templates/recipes/reusable/recipe.html
<div class="recipe recipe-list-item">
  {% if recipe.cover %}
    <div class="recipe-cover">
      <a href="{% url 'recipes:recipe' recipe.id %}">
        <img src="{{recipe.cover.url}}" alt="Temporario"><!--varible-->
      </a>
    </div>
  {% endif %}
  <div class="recipe-title-container">
    <h2 class="recipe-title">
      <a href="{% url 'recipes:recipe' recipe.id %}">
        {{ recipe.title }}
      </a>
    </h2><!--varible-->
  </div>
  <div class="recipe-author">
    {% if recipe.author is not None %}
      <span class="recipe-author-item">
        <i class="bi bi-person-fill"></i>

        {% if recipe.author.first_name %}
          {{recipe.author.first_name}}{{recipe.author.last_name}}<!--varible-->
        {% else %}
          {{recipe.author.username}}
        {% endif %}

      </span>
    {% endif %}
    <span class="recipe-author-item">
      <i class="bi bi-calendar-date"></i>
        {{ recipe.created_at|date:"d/m/Y" }} às {{ recipe.created_at|date:"H:i" }}<!--varible-->
    </span>
    {% if recipe.category is not None %}
      <span class="recipe-author-item">
        <a href="{% url 'recipes:category' recipe.category.id %}">
          <i class="bi bi-stack"></i>
          <span>{{recipe.category.name}}</span><!--varible-->

        </a>
      </span>
    {% endif %}
  </div>
  <div class="recipe-content">
    <p>{{recipe.description}}</p><!--varible-->
  </div>
  <div class="recipe-meta-container">
    <div class="recipe-meta recipe-preparation">
      <h3 class="recipe-meta-title"><i class="bi bi-stopwatch-fill"></i> Preparo</h3>
      <div class="recipe-meta-text">
        {{recipe.preparation_time}} {{recipe.preparation_time_unit}}<!--varible-->
      </div>
    </div>
    <div class="recipe-meta recipe-servings">
      <h3 class="recipe-meta-title"><i class="bi bi-database"></i> Porcoes</h3>
      <div class="recipe-meta-text">
        {{recipe.servings}} {{recipe.servings_unit}}<!--varible-->
      </div>
    </div>
  </div>
  {% if is_detail_page is not True %}<!--varible-->
  <footer class="recipe-footer">
    <a href="{% url 'recipes:recipe' recipe.id %}" class="button button-dark button-full-width recipe-read-more">
      <i class="bi bi-eye-fill"></i>
      <span>Ver mais...</span>
    </a>
  </footer>

  {% endif %}
  {% if is_detail_page is True %}
  <!--varible se for detail verdadeiro mostra -->
    <div class="preparation-steps">
      {% if recipe.preparation_steps_is_html is True %}
        {{recipe.preparation_steps|safe }}
      {% else %}
        {{recipe.preparation_steps|linebreaksbr }}<!--varible-->
    </div>
      {% endif %}
  {% endif %}



</div>

recipes/templates/recipes/reusable/search.html
<div class="search-container">
  <div class="container">
    <form class="search-form" action="" method="get">

      <input class="search-input" type="search" name="search" placeholder="Digite para pesquisar" id="">
      <button class="search-button" type="submit">
        <i class="bi bi-search"></i>
      </button>


    </form>
  </div>
</div>

recipes/templates/recipes/sobre.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=h, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>sobre</h1>
</body>
</html>